Update deployment workflow to improve project navigation
- Enhanced the deployment script to include additional project directory checks, ensuring more robust navigation to the correct project folder.
- Adjusted debug information to focus on the services directory for better clarity during deployment.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -18,11 +18,10 @@ jobs:
           script: |
             echo "--- Debug Info ---"
             pwd
-            ls -la
+            ls -la ~/services
             echo "--- Navigating to project ---"
-            cd ~/services/cat-health-control || cd ~/cat-health-control || (echo "Project folder not found!" && exit 1)
+            cd ~/services/cat-health-control-bot || cd ~/services/cat-health-control || cd ~/cat-health-control || (echo "Project folder not found!" && exit 1)
             pwd
-            ls -la
             echo "--- Deployment ---"
             git pull origin master
             docker compose build frontend
